# Generated by Django 4.2.19 on 2025-02-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ocupations',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'ocupations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='users')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
